Develop by kuba
dehydrogenaza/vacc-calendar pull request #3
Opened 2023-01-16 14:16 UTC by Jakub112358

2023-01-16 18:07 UTC, dehydrogenaza requested changes

2023-01-16 18:07 UTC, dehydrogenaza commented on src/main/java/org/dehydrogenaza/data/DiseaseEnum.java
> +public enum DiseaseEnum {
Wg konwencji nie daje się słówka "enum" w nazwie enumów.
```suggestion
public enum Disease {
```

2023-01-16 18:07 UTC, dehydrogenaza commented on src/main/java/org/dehydrogenaza/data/RecommendationEnum.java
> +public enum RecommendationEnum {
```suggestion
public enum Recommendation {
// alternatywnie: RecommendationLevel
```

2023-01-16 18:07 UTC, dehydrogenaza commented on src/main/java/org/dehydrogenaza/data/VaccTagEnum.java
> +public enum VaccTagEnum {
```suggestion
public enum VaccTag {
```

2023-01-16 18:07 UTC, dehydrogenaza commented on src/main/java/org/dehydrogenaza/data/VaccineScheme.java
> +    private HashMap<Integer, Integer[]> recommendedOffsets;
Może ładniej byłoby stworzyć wewnętrzną klasę Range z polami min i max.

2023-01-16 18:07 UTC, dehydrogenaza commented on src/main/java/org/dehydrogenaza/data/VaccineType.java
> +        public Builder withTags (List<VaccTagEnum> tags){
W builderach które budują listy często dodaje się po 1 elemencie. IMO tutaj byłoby tak wygodniej. Pustą listę twórz w konstruktorze, a tutaj dodawaj do niej 1 tag (żeby użytkownik buildera nie musiał tworzyć ręcznie listy tagów).

2023-01-17 12:26 UTC, Jakub112358 commented on pom.xml
> +<!--    <tomcat.version>7.0.108</tomcat.version>-->
Pewnie się gdzieś wkradł przy konfiguracji, raczej niepotrzebny.

2023-01-17 12:26 UTC, Jakub112358 commented on src/main/java/org/dehydrogenaza/data/DiseaseEnum.java
> +public enum DiseaseEnum {
ok.

2023-01-17 12:26 UTC, Jakub112358 commented on src/main/java/org/dehydrogenaza/data/VaccineScheme.java
> +    private HashMap<Integer, Integer[]> recommendedOffsets;
Może ładniej, nie wiem. Z jednej strony byłoby trochę czytelniej, z drugiej nie wiem czy to nie jest przesadne rozdmuchiwanie programu, żeby robić klasę która ma tylko 2 inty i nic więcej. Chyba, że ta klasa wewnętrzna by miała jeszcze jakieś metody inne niż typowe, to wtedy spoko. Myślę, że można tu na razie dodać komentarz i najwyżej w przyszłości wydzielić klasę.

2023-01-17 12:55 UTC, dehydrogenaza commented on src/main/java/org/dehydrogenaza/data/VaccineScheme.java
> +    private HashMap<Integer, Integer[]> recommendedOffsets;
OK, na razie na pewno może być, ale w przyszłości jak to ma pójść do portfolio to jest to jedna z rzeczy do refactorowania.

2023-01-17 13:00 UTC, dehydrogenaza approved these changes

2023-01-17 13:01 UTC, merged